#!/bin/bash
# AXEL - Finance Department Agent Runner
# Market monitoring, opportunity identification, financial intelligence

AGENT_NAME="AXEL"
WORKSPACE="$HOME/.openclaw"
AGENT_DIR="$WORKSPACE/agents/$AGENT_NAME"
OUTPUT_DIR="$AGENT_DIR/output"
MEMORY_DIR="$AGENT_DIR/memory"
DAILY_BRIEFS="$MEMORY_DIR/daily-briefs"

mkdir -p "$OUTPUT_DIR" "$DAILY_BRIEFS"

log() {
    echo "[$(date '+%H:%M:%S')] AXEL: $1" >> "$AGENT_DIR/agent.log"
}

update_heartbeat() {
    echo '{"timestamp":'$(date +%s)',"status":"working","task":"'$1'"}' > "$AGENT_DIR/heartbeat.json"
}

# Function to get crypto prices
get_crypto_prices() {
    log "Fetching crypto prices..."
    
    # Use CoinGecko API (free tier)
    curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum&vs_currencies=usd&include_24hr_change=true" 2>/dev/null | \
        python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    for coin, info in data.items():
        price = info.get('usd', 0)
        change = info.get('usd_24h_change', 0)
        print(f'{coin.upper()}: \${price:,.2f} ({change:+.2f}%)')
except:
    pass
" > "$OUTPUT_DIR/crypto-prices.txt"
}

# Function to get fear & greed
get_fear_greed() {
    log "Fetching sentiment data..."
    
    curl -s "https://api.alternative.me/fng/" 2>/dev/null | \
        python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    value = data.get('data', [{}])[0].get('value', 'N/A')
    classification = data.get('data', [{}])[0].get('value_classification', 'N/A')
    print(f'{value}/100 ({classification})')
except:
    print('N/A')
" > "$OUTPUT_DIR/fear-greed.txt"
}

# Function to generate daily brief
generate_daily_brief() {
    log "Generating daily brief..."
    update_heartbeat "generating_brief"
    
    local brief_file="$DAILY_BRIEFS/brief-$(date +%Y%m%d).md"
    
    cat > "$brief_file" << EOF
# AXEL Daily Brief - $(date '+%A, %B %d, %Y')

## Market Snapshot

### Crypto
$(cat "$OUTPUT_DIR/crypto-prices.txt" 2>/dev/null || echo "Data pending")

### Sentiment
- Fear & Greed Index: $(cat "$OUTPUT_DIR/fear-greed.txt" 2>/dev/null || echo "N/A")

## Key Movements
$(if grep -q "+" "$OUTPUT_DIR/crypto-prices.txt" 2>/dev/null; then
    echo "- Positive momentum detected in select assets"
fi)
$(if grep -q "-" "$OUTPUT_DIR/crypto-prices.txt" 2>/dev/null; then
    echo "- Some assets showing pullback"
fi)

## Opportunities Flagged
🔍 Monitoring BTC and ETH for accumulation opportunities
   - Risk: Medium | Timeframe: Medium-term

## Risk Alerts
$(if [ -f "$OUTPUT_DIR/fear-greed.txt" ]; then
    FEAR_VALUE=$(cat "$OUTPUT_DIR/fear-greed.txt" | grep -oE '[0-9]+' | head -1)
    if [ -n "$FEAR_VALUE" ] && [ "$FEAR_VALUE" -lt 25 ]; then
        echo "⚠️ Extreme fear detected - potential opportunity zone"
    elif [ -n "$FEAR_VALUE" ] && [ "$FEAR_VALUE" -gt 75 ]; then
        echo "⚠️ Extreme greed detected - caution warranted"
    else
        echo "✅ Sentiment in neutral range"
    fi
fi)

## Notes
- Advisory only. No trading recommendations.
- DYOR (Do Your Own Research)
- Past performance does not indicate future results

---
Generated by AXEL Finance Department
Time: $(date '+%H:%M %Z')
Status: $(if [ -s "$OUTPUT_DIR/crypto-prices.txt" ]; then echo "Data retrieved"; else echo "API pending"; fi)
EOF
    
    log "Daily brief saved: $brief_file"
    
    # Add to Mission Control notifications
    python3 << PYEOF
import json

try:
    with open('$WORKSPACE/mission-control/state.json', 'r') as f:
        state = json.load(f)
    
    if 'notifications' not in state:
        state['notifications'] = []
    
    state['notifications'].append({
        'type': 'daily_brief',
        'agent': 'AXEL',
        'title': 'Daily Market Brief Ready',
        'time': '$(date -u +%Y-%m-%dT%H:%M:%SZ)',
        'read': False
    })
    
    with open('$WORKSPACE/mission-control/state.json', 'w') as f:
        json.dump(state, f, indent=2)
except Exception as e:
    print(f"Error: {e}")
PYEOF
}

# Main AXEL loop
log "AXEL Finance Department starting up..."

# Track last brief date
LAST_BRIEF_DATE=""

while true; do
    CURRENT_DATE=$(date +%Y%m%d)
    CURRENT_HOUR=$(date +%H)
    
    # Generate daily brief at 7 AM
    if [ "$CURRENT_HOUR" -ge 7 ] && [ "$LAST_BRIEF_DATE" != "$CURRENT_DATE" ]; then
        log "Starting daily brief generation..."
        
        update_heartbeat "market_scan"
        get_crypto_prices
        get_fear_greed
        
        generate_daily_brief
        
        LAST_BRIEF_DATE="$CURRENT_DATE"
        log "Daily brief complete"
    fi
    
    # Hourly price checks
    if [ $(($(date +%s) % 3600)) -lt 60 ]; then
        log "Hourly price check..."
        update_heartbeat "price_check"
        get_crypto_prices
    fi
    
    update_heartbeat "idle"
    
    # Sleep for 1 minute (check frequently for 7 AM trigger)
    sleep 60
done
