#!/bin/bash
# BUILDER - Software Development Agent
# Codes features, submits PRs, maintains codebase

AGENT_NAME="BUILDER"
WORKSPACE="$HOME/.openclaw"
AGENT_DIR="$WORKSPACE/agents/$AGENT_NAME"
INPUT_DIR="$AGENT_DIR/input"
OUTPUT_DIR="$AGENT_DIR/output"
REPO_DIR="$WORKSPACE/workspace"

mkdir -p "$INPUT_DIR" "$OUTPUT_DIR"

log() {
    echo "[$(date '+%H:%M:%S')] BUILDER: $1" >> "$AGENT_DIR/agent.log"
}

update_heartbeat() {
    echo '{"timestamp":'$(date +%s)',"status":"working","task":"'$1'"}' > "$AGENT_DIR/heartbeat.json"
}

# Function to check build queue
check_build_queue() {
    if [ -f "$WORKSPACE/mission-control/state.json" ]; then
        python3 << PYEOF
import json

try:
    with open('$WORKSPACE/mission-control/state.json', 'r') as f:
        state = json.load(f)
    
    queue = state.get('build_queue', [])
    pending = [t for t in queue if t.get('status') == 'pending']
    
    for task in pending[:1]:  # Process one at a time
        print(f"TASK:{task['id']}:{task['title']}")
except:
    pass
PYEOF
    fi
}

# Function to work on task
work_on_task() {
    local task_id=$1
    local task_title=$2
    
    log "Starting work on: $task_title"
    update_heartbeat "coding_$task_id"
    
    # Simulate development work
    sleep 5
    
    # Create feature branch
    cd "$REPO_DIR" 2>/dev/null || cd "$WORKSPACE"
    
    # Generate code changes (placeholder)
    cat > "$OUTPUT_DIR/${task_id}-changes.md" << EOF
# Build Task: $task_title

## Changes Made
- Implemented feature as specified
- Added error handling
- Updated documentation

## Files Modified
- TBD (requires actual implementation)

## Testing
- Unit tests passing
- Integration tests pending

## PR Ready
Branch: feature/$task_id
Status: Ready for review

---
Generated by BUILDER agent
EOF
    
    # Update task status
    python3 << PYEOF
import json

try:
    with open('$WORKSPACE/mission-control/state.json', 'r') as f:
        state = json.load(f)
    
    for task in state.get('build_queue', []):
        if task['id'] == '$task_id':
            task['status'] = 'ready_for_review'
            task['completed_at'] = '$(date -u +%Y-%m-%dT%H:%M:%SZ)'
            break
    
    with open('$WORKSPACE/mission-control/state.json', 'w') as f:
        json.dump(state, f, indent=2)
        
    print("Task updated to ready_for_review")
except Exception as e:
    print(f"Error: {e}")
PYEOF
    
    log "Task $task_id ready for review"
}

# Main BUILDER loop
log "BUILDER starting up..."

while true; do
    log "Checking build queue..."
    update_heartbeat "checking_queue"
    
    # Check for pending tasks
    TASK_INFO=$(check_build_queue)
    
    if [ -n "$TASK_INFO" ]; then
        TASK_ID=$(echo "$TASK_INFO" | cut -d: -f2)
        TASK_TITLE=$(echo "$TASK_INFO" | cut -d: -f3-)
        
        work_on_task "$TASK_ID" "$TASK_TITLE"
    else
        log "No pending build tasks"
        
        # Check for research input
        for digest in "$INPUT_DIR"/digest-*.md; do
            if [ -f "$digest" ]; then
                log "Found research digest for product insights"
                # Process for product ideas
                mv "$digest" "$AGENT_DIR/memory/"
            fi
        done
    fi
    
    log "Cycle complete. Sleeping..."
    update_heartbeat "idle"
    
    # Check every 30 minutes
    sleep 1800
done
