#!/bin/bash
# RESEARCH - Intelligence Gathering Agent
# Scrapes social media, news, trends for content and product insights

AGENT_NAME="RESEARCH"
WORKSPACE="$HOME/.openclaw"
AGENT_DIR="$WORKSPACE/agents/$AGENT_NAME"
OUTPUT_DIR="$AGENT_DIR/output"
MEMORY_DIR="$AGENT_DIR/memory"

mkdir -p "$OUTPUT_DIR" "$MEMORY_DIR"

log() {
    echo "[$(date '+%H:%M:%S')] RESEARCH: $1" >> "$AGENT_DIR/agent.log"
}

update_heartbeat() {
    echo '{"timestamp":'$(date +%s)',"status":"working","task":"'$1'"}' > "$AGENT_DIR/heartbeat.json"
}

# Main RESEARCH loop
log "RESEARCH starting up..."

while true; do
    log "Beginning research cycle"
    update_heartbeat "scraping"
    
    # 1. YouTube trending (AI/automation focus)
    log "Scanning YouTube trends..."
    # Use yt-dlp to get trending topics
    yt-dlp --flat-playlist --print "%(title)s|%(uploader)s" \
        "https://www.youtube.com/feed/trending" 2>/dev/null | \
        grep -i "AI\|automation\|agent" | head -10 > "$OUTPUT_DIR/youtube-trends.txt"
    
    # 2. X/Twitter search (if API available)
    log "Checking X/Twitter..."
    # Placeholder for X API integration
    echo "X_API_PENDING" > "$OUTPUT_DIR/x-status.txt"
    
    # 3. Reddit monitoring
    log "Scanning Reddit..."
    curl -s "https://www.reddit.com/r/artificial/hot.json?limit=10" 2>/dev/null | \
        python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    for post in data.get('data', {}).get('children', []):
        title = post.get('data', {}).get('title', '')
        if any(k in title.lower() for k in ['ai', 'agent', 'automation', 'openclaw']):
            print(title[:100])
except:
    pass
" > "$OUTPUT_DIR/reddit-hot.txt"
    
    # 4. Generate research digest
    log "Generating digest..."
    
    cat > "$OUTPUT_DIR/digest-$(date +%Y%m%d-%H%M).md" << EOF
# Research Digest - $(date '+%Y-%m-%d %H:%M')

## YouTube Trends
$(cat "$OUTPUT_DIR/youtube-trends.txt" 2>/dev/null | head -5)

## Reddit Hot
$(cat "$OUTPUT_DIR/reddit-hot.txt" 2>/dev/null | head -5)

## Content Ideas
- AI agent frameworks
- Automation tutorials
- OpenClaw use cases

## Product Insights
- Market demand for AI automation
- Competitor analysis pending
- Feature gaps identified

---
Generated by RESEARCH agent
EOF
    
    # 5. Feed to CONTENT agent
    log "Feeding content ideas to CONTENT..."
    cp "$OUTPUT_DIR/digest-$(date +%Y%m%d-%H%M).md" "$WORKSPACE/agents/CONTENT/input/"
    
    # 6. Feed to BUILDER for product insights
    log "Feeding product insights to BUILDER..."
    cp "$OUTPUT_DIR/digest-$(date +%Y%m%d-%H%M).md" "$WORKSPACE/agents/BUILDER/input/"
    
    log "Cycle complete. Sleeping..."
    update_heartbeat "idle"
    
    # Sleep for 1 hour
    sleep 3600
done
